CREATE TABLE IF NOT EXISTS kv_store (
    id INT AUTO_INCREMENT PRIMARY KEY,
    key_name VARCHAR(191) NOT NULL UNIQUE,
    value LONGTEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
